FROM python:3.11

ENV DEBIAN_FRONTEND=noninteractive
ENV VENV_PATH="/env"
ENV PATH="${VENV_PATH}/bin:${VENV_PATH}:${PATH}"
ENV PYTHONNOUSERSITE=true

RUN apt-get update && apt-get install -y \
      build-essential libcurl4-openssl-dev zlib1g-dev libfftw3-dev libc++-dev hdf5-tools \
      openjdk-17-jdk-headless libbz2-dev liblzma-dev procps libfftw3-dev ant

RUN python -m venv "${VENV_PATH}" && \
    . "${VENV_PATH}/bin/activate" && \
    pip install jupyterlab papermill && \
    pip install 'snapatac2[recommend]'==2.7.0

COPY Dockerfile /docker/
RUN chmod -R 755 /docker
