FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

ENV VIRTUAL_ENV=/env
ENV PATH=$VIRTUAL_ENV/bin:$VIRTUAL_ENV:$PATH
ENV NUMBA_CACHE_DIR=/tmp
ENV DEBIAN_FRONTEND=noninteractive
ENV STARDIST_PRETRAINED_MODEL=2D_versatile_fluo

RUN apt-get update && apt-get install -y \
        procps git wget build-essential \
        python3 python-is-python3 python3-dev python3-venv

RUN python -m venv $VIRTUAL_ENV && \
    . $VIRTUAL_ENV/bin/activate && \
    pip install --upgrade pip wheel 'setuptools<81'

ENV STARDIST_VERSION=0.9.2
RUN . $VIRTUAL_ENV/bin/activate && \
    pip install 'tensorflow[and-cuda]==2.15.*' && \
    pip install 'numpy<2' && \
    pip install stardist==$STARDIST_VERSION csbdeep==0.8.2 gputools==0.2.16 edt==3.0.0 ImageTileProcessor==0.2.1 'numpy<2'

RUN . $VIRTUAL_ENV/bin/activate && \
    python -c "from stardist.models import StarDist2D; StarDist2D.from_pretrained('${STARDIST_PRETRAINED_MODEL}')"

COPY Dockerfile /docker/
RUN chmod -R 755 /docker
