FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

SHELL ["/bin/bash", "-c"]

ARG NICHECOMPASS_VERSION="0.3.0"
ARG TORCH="2.2.0"
ARG CUDA="cu121"

ENV VENV_PATH="/env"
ENV PATH="${VENV_PATH}/bin:${PATH}"
ENV NUMBA_CACHE_DIR=/tmp
ENV PYTHONNOUSERSITE=1
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential procps git python3 python3-dev python3-venv python3-pip python-is-python3 wget locales && \
    locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# install python packages
RUN python3 -m venv $VENV_PATH && \
    . "$VENV_PATH/bin/activate" && \
    pip install --upgrade pip wheel setuptools uv && \
    uv pip install "torch==${TORCH}+${CUDA}" --index-url "https://download.pytorch.org/whl/${CUDA}" && \
    uv pip install "numpy==1.*" pyg_lib torch_scatter torch_sparse -f "https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html" && \
    uv pip install papermill jupyterlab ipykernel gdown "nichecompass[all]==${NICHECOMPASS_VERSION}"

# get bedtools
RUN wget -O /usr/bin/bedtools https://github.com/arq5x/bedtools2/releases/download/v2.31.0/bedtools.static && \
    chmod a+x /usr/bin/bedtools

# import python packages to pre-download ref data
COPY nichecompass_import.py /app/nichecompass_import.py
RUN . "$VENV_PATH/bin/activate" && \
    python /app/nichecompass_import.py

COPY Dockerfile /docker/
RUN chmod -R 755 /docker
