FROM nvcr.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

SHELL ["/bin/bash", "-c"]

ARG NICHECOMPASS_VERSION="0.1.2"

ENV PYTHONNOUSERSITE=1
ENV PATH="/env/bin:${PATH}"

RUN apt-get update && apt-get install -y --no-install-recommends \
    procps git python3 python3-dev python3-venv python3-pip python-is-python3 wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# get bedtools
RUN wget -O /usr/bin/bedtools https://github.com/arq5x/bedtools2/releases/download/v2.31.0/bedtools.static && \
    chmod a+x /usr/bin/bedtools

# install python packagess
RUN TORCH=2.2.0 CUDA=cu118 && \
    python3 -m venv /env && \
    source /env/bin/activate && \
    pip install -U pip wheel --no-cache-dir && \
    pip install "torch==${TORCH}+${CUDA}" --index-url "https://download.pytorch.org/whl/${CUDA}" --no-cache-dir && \
    pip install pyg_lib torch_scatter torch_sparse -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html && \
    pip install papermill jupyterlab ipykernel "nichecompass[all]==${NICHECOMPASS_VERSION}" --no-cache-dir

COPY Dockerfile /