FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

SHELL ["/bin/bash", "-c"]

ARG NICHECOMPASS_VERSION="0.2.3"
ARG TORCH="2.2.0"
ARG CUDA="cu121"

ENV VENV_PATH="/env"
ENV PATH="${VENV_PATH}/bin:${PATH}"
ENV PIP_NO_CACHE_DIR=false
ENV NUMBA_CACHE_DIR=/tmp
ENV PYTHONNOUSERSITE=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    procps git python3 python3-dev python3-venv python3-pip python-is-python3 wget locales && \
    locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# get bedtools
RUN wget -O /usr/bin/bedtools https://github.com/arq5x/bedtools2/releases/download/v2.31.0/bedtools.static && \
    chmod a+x /usr/bin/bedtools

# install python packages
# Pin NumPy/SciPy versions to avoid compatibility issues
RUN python3 -m venv $VENV_PATH && \
    . $VENV_PATH/bin/activate && \
    pip install -U pip wheel setuptools && \
    pip install "numpy==1.25.*" "scipy==1.15.3" && \
    pip install "torch==${TORCH}+${CUDA}" --index-url "https://download.pytorch.org/whl/${CUDA}" && \
    pip install "pyg_lib==0.4.0+pt22cu121" "torch_scatter==2.1.2+pt22cu121" "torch_sparse==0.6.18+pt22cu121" \
    -f "https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html"

RUN . $VENV_PATH/bin/activate && \
    pip install papermill jupyterlab ipykernel "nichecompass[all]==${NICHECOMPASS_VERSION}" 'squidpy[interactive]'

COPY Dockerfile /docker/
RUN chmod -R 755 /docker
