FROM rocker/r-ver:4.3.1

ENV DEBIAN_FRONTEND=noninteractive
ENV VENV_PATH=/env
ENV PATH=$VENV_PATH/bin:$VENV_PATH:$PATH
ENV NUMBA_CACHE_DIR=/tmp

# Add deadsnakes PPA for Python 3.12+
RUN apt-get update && apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update

RUN apt-get install -y \
        python3.12 python3.12-dev python3.12-venv \
        libpcre2-dev libbz2-dev zlib1g-dev liblzma-dev libcurl4-openssl-dev \
        libxml2-dev libicu-dev libcairo2-dev \
        build-essential git

# Point python/python3 to 3.12
RUN update-alternatives --install /usr/bin/python  python  /usr/bin/python3.12 1 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1

RUN python -m venv $VENV_PATH && \
    . $VENV_PATH/bin/activate && \
    pip install --upgrade pip setuptools wheel && \
    pip install jupyterlab && \
    pip install "rpy2>=3.5.11,<3.6" && \
    pip install pertpy[de]

RUN . $VENV_PATH/bin/activate && \
    pip install anndata2ri

RUN Rscript -e "install.packages(c('BiocManager', 'statmod','tidyverse','reshape2','patchwork'))" && \
    Rscript -e "BiocManager::install('edgeR')"

COPY Dockerfile /docker/
RUN chmod -R 755 /docker
ENTRYPOINT ["/env/bin/python"]
